export default {
  produk: [
    {
      _id: '21',
      title: 'Sepatu Nike',
      category: 'pakaian',
      image: '/assets/sepatu-nike.jpg',
      price: 60,
      rating: 4.5,
      numReviews: 10,
      author: 'Yolanda',
    },
    {
      _id: '22',
      title: 'Sepatu Adidas',
      category: 'pakaian',
      image: '/assets/sepatu-adidas.jpg',
      price: 70,
      rating: 4,
      numReviews: 12,
      author: 'Adam Bisyahri',
    },
    {
      _id: '23',
      title: 'Indomie',
      category: 'makanan',
      image: '/assets/indomie.jpg',
      price: 5,
      rating: 3,
      numReviews: 7,
      author: 'Yolanda',
    },
    {
      _id: '24',
      title: 'Indomie Goreng',
      category: 'makanan',
      image: '/assets/indomie-goreng.jpg',
      price: 4,
      rating: 4,
      numReviews: 15,
      author: 'Adam Bisyahri',
    },
    {
      _id: '25',
      title: 'Iphone 12',
      category: 'elektronik',
      image: '/iphone12.jpg',
      price: 800,
      rating: 5,
      numReviews: 23,
      author: 'Yolanda',
    },
    {
      _id: '26',
      title: 'Samsung Galaxy',
      category: 'elektronik',
      image: '/assets/samsung-galaxy.jpg',
      price: 500,
      rating: 5,
      numReviews: 18,
      author: 'Adam Bisyahri',
    },
    {
      _id: '27',
      title: 'Speaker JBL',
      category: 'elektronik',
      image: '/assets/speaker-jbl.jpg',
      price: 60,
      rating: 4,
      numReviews: 10,
      author: 'Yolanda',
    },
    {
      _id: '28',
      title: 'Speaker Bose',
      category: 'elektronik',
      image: '/assets/speaker-bose.jpg',
      price: 60,
      rating: 4.5,
      numReviews: 12,
      author: 'Adam Bisyahri',
    },
    {
      _id: '29',
      title: 'Rokok Sampoerna',
      category: 'makanan',
      image: '/assets/rokok-sampoerna.jpg',
      price: 5,
      rating: 5,
      numReviews: 7,
      author: 'Yolanda',
    },
    {
      _id: '30',
      title: 'Jasa Titip Jerman-Indo 15 Agustus',
      category: 'jasa titip',
      image: '/assets/jasa-titip.jpg',
      price: 15,
      rating: 4.5,
      numReviews: 14,
      author: 'Yolanda',
    },
    {
      _id: '31',
      title: 'Titip Bagasi Indo-Jerman 22 Desember',
      category: 'jasa titip',
      image: '/assets/titip-bagasi.jpg',
      price: 14,
      rating: 2,
      numReviews: 15,
      author: 'Adam Bisyahri',
    },
    {
      _id: '32',
      title: 'Seblak',
      category: 'makanan',
      image: '/assets/seblak.jpg',
      price: 7,
      rating: 1,
      numReviews: 10,
      author: 'Yolanda',
    },
    {
      _id: '33',
      title: 'Tas Louis Vuitton',
      category: 'pakaian',
      image: '/assets/louis-vuitton.jpg',
      price: 1000,
      rating: 4.5,
      numReviews: 2,
      author: 'Adam Bisyahri',
    },
  ],
};
